### ISSUE TITLE
Can you add blockit or similar adblock for gtkwebkit in photopea

### ISSUE THREAD

**Issue by prateekmedia** [vikdevelop/photopea_app#1]
Blockit => https://github.com/dudik/blockit

**Comment by vikdevelop** [comment]
Thanks for the tip.But I don't want to "destroy" Photopea's only source of money for the developer.

**Comment by JaneSmith** [comment]
I installed this, and then immediately uninstalled it because of this. No offence, but without some kind off adblocker this wrapper is pointless.

**Comment by krodelabestiole** [comment]
I was just wondering what was the point of this wrapper...

Make it easier to install than a [GNOME web app](https://help.gnome.org/users/epiphany/stable/browse-webapps.html.en) ?
It would make sense but then why would you change its name and logo ?

Plus I can't find any info on this project, all the doc is about Photopea.
Flathub marks it as FOSS while it is not technically true.

**Comment by vikdevelop** [comment]
1. The application name and icon has been changed, because Flathub considered the original name and icon a trademark infringement, see https://github.com/flathub/com.github.vikdevelop.photopea_app/issues/10
2. When I tried to publish this app on Flathub, I was notified to change the license type from proprietary to the license of this Github repository, which is MIT, see https://github.com/flathub/flathub/pull/2504#discussion_r708515789

   In the description of this app, I am introducing the following text: 
NOTES: This application is unofficial wrapper of web application Photopea. Only the Electron wrapper itself is licensed by MIT. The web application is under a proprietary license.

**Comment by krodelabestiole** [comment]
ah, ok, legit then !
thank you for your explanations and dedication.

**Comment by JaneSmith** [comment]
For anyone that's interested, this is what I've settled on:

I'm now running Photopea as standalone web app via Quick Web Apps instead. You can find Quick Web Apps on Flathub, and it basically just sets up a custom Firefox profile and a .desktop file to launch Firefox into that profile. You could do it manually without Quick Web Apps if you prefer.

This method lets me use the full power of Firefox, instead of something poor like Epiphany (which I think is what GNOME Web Apps uses, if that feature even still exists). So I now get full GPU acceleration and 120 Hz frame rate, Firefox-Gnome-Theme for a more native look, uBlock Origin for ad blocking, and Violentmonkey for site extensions. All as if it's a standalone app.

I'm very happy with this setup. It's still called Firefox and uses the Firefox icon in the Alt+Tab switcher or GNOME overview, but otherwise it functions like its own app and doesn't affect my normal running web browser at all. And no ads! Since it's using its own profile, it doesn't share history, cookies, bookmarks, etc. with my normal Firefox, and I've set it up to not even save any history.

Here's a screenshot:

![Screenshot from 2024-09-06 01-36-14](https://github.com/user-attachments/assets/dae4b99c-7e17-41ce-b7ca-f6d150c118dc)
